language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3.3

install:
  - composer config -g -- disable-tls true
  - composer config -g secure-http false
  - composer self-update
  - composer install --dev --prefer-dist

cache:
  directories:
  - vendor

script:
  - php vendor/bin/phpunit --verbose
  - php vendor/bin/phpcs